### ISSUE TITLE
STAY AWAY

### ISSUE THREAD

**Issue by ricardo-nolan** [ajpsp5/ethos-auto-miner#1]
Cute, except for the part where you set it to mine for you every 6 hours and aren't informing users.

Someone who isn't a programmer wouldn't know, and you don't inform them, or give them the choice to do so or not.

To me this screams "STAY AWAY!".

I'll admit that I like your code in general, but I don't like devs who trick users into mining for them.

As a developer, you either make open source code for the community or you don't.

This is a slap in the face for devs like myself, who freely share our code with the community. Obviously I accept donations, but I don't force people to donate.

If you look at my code, there is nothing there where I force any user to do anything they don't want.

**Comment by ajpsp5** [comment]
@foraern 

No, It mines one hour a day, which is roughly less than $0.15 a day. The donation is to help build an mobile app for monitoring Ethos Rigs. I will update the ReadMe, thank you for pointing that out. 

If you are developer, I want to invite you to help me improve the program and build the mobile app.

**Comment by ajpsp5** [comment]
@foraern 

I've updated the ReadMe, thank you again for your feedback. If you are developer and interested in helping me please contact me.
