### ISSUE TITLE
Wont run, errors I'm not sure whats wrong.

### ISSUE THREAD

**Issue by 1990camaro** [ajpsp5/ethos-auto-miner#2]
![github_1](https://user-images.githubusercontent.com/11812456/39737214-916dedf6-5249-11e8-9b96-d17f65a24680.jpg)
![github_2](https://user-images.githubusercontent.com/11812456/39737217-946ad488-5249-11e8-85c0-37565170f208.jpg)
![github_3](https://user-images.githubusercontent.com/11812456/39737221-969df186-5249-11e8-8339-1d770a1a206d.jpg)

First off, I want to say if I can get this thing working you are definitely getting a beer... lol. I have uploaded pictures of the command line, and my config files. If you could tell me what I'm doing wrong I'd appreciate it. I'm not sure why it tells me the info is wrong as I set it all up as you had advised.

**Comment by ajpsp5** [comment]
@1990camaro 

I will look into this and get back with you as soon as I can.

**Comment by ajpsp5** [comment]
Just by looking at your screenshots. The pool is returning saying your BTC address is invalid. I will try to copy your settings. You might see one of my miners mining for you.

**Comment by ajpsp5** [comment]
@1990camaro

So it looks like you put the wrong rig name in for that specific miner.

In your screenshot of the terminal the rig name is “2954ad” but you set the rig name as “2854ad” in the config.

Simple mistake, so just change the name and you will be up mining. Happy Mining!
