### ISSUE TITLE
alerts

### ISSUE THREAD

**Issue by denwill** [ajpsp5/ethos-auto-miner#6]
After removing this software, I still get email alerts. Anyway remove the alerts?

**Comment by ajpsp5** [comment]
What is your email? I can check the server.

**Comment by ajhead11** [comment]
Hey ajpsp5,
Same issue for me. I'm getting 10 alerts per day! Can u remove my email from the server? Adamjhead@gmail.com. thanks

**Comment by ajpsp5** [comment]
@ajhead11 

Your email has been removed. Be sure to remove the email rule from your config.
